<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Resume</name>
   <tag></tag>
   <elementGuidId>2f60a220-a05e-4a00-9eed-87302b868a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='MessagingDestinationControlList:MessagingDestinationControlListScreen:MessagingDestinationControlList_ResumeButton-btnEl']/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id, 'ResumeButton')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d238fcb9-26b5-40ee-a760-6d411bc1d9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ResumeButton</value>
      <webElementGuid>75835694-43dc-4480-8240-85a329c1b288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>e3742f56-716e-4575-af99-98897ce417be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>bcf2b1ae-c414-4e5c-a7cb-35e1727d8680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-toolbar-small</value>
      <webElementGuid>02ba777d-d275-4742-913d-7120fdf02dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resume</value>
      <webElementGuid>4b67cbbb-11af-4a1d-a400-281c3ec25f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MessagingDestinationControlList:MessagingDestinationControlListScreen:MessagingDestinationControlList_ResumeButton-btnInnerEl&quot;)</value>
      <webElementGuid>0ecd4988-b9a1-4bb1-afb2-f67cf2ad2ce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='MessagingDestinationControlList:MessagingDestinationControlListScreen:MessagingDestinationControlList_ResumeButton-btnInnerEl']</value>
      <webElementGuid>a2ccc68f-6a99-4856-b1f8-501d94decb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='MessagingDestinationControlList:MessagingDestinationControlListScreen:MessagingDestinationControlList_ResumeButton-btnEl']/span[2]</value>
      <webElementGuid>9d5131df-5ab3-4703-ae67-78d4f94e5073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/following::span[4]</value>
      <webElementGuid>aabaf59a-46d1-4750-9e06-8cad357934a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/a[2]/span/span/span[2]</value>
      <webElementGuid>fc992411-22d5-4912-95c7-6e08edfda2db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
