<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_RestartMessagingEngine</name>
   <tag></tag>
   <elementGuidId>99cff093-d164-4387-80b5-fbe5d5ffb920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id, 'RestartMessagingEngineButton')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c55f0ce6-86a3-47fd-a7bd-98b1e270e01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RestartMessagingEngineButton</value>
      <webElementGuid>cc19ad37-f8ff-4a22-a62e-0815ce507c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>268e3c8b-8f15-4e8a-b306-4b1b57e4e43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>fb6b895c-2ad1-4b3e-ad73-022d3bc60e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-toolbar-small</value>
      <webElementGuid>f7a816bd-1d21-4e10-979d-82237bee4444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Restart Messaging Engine</value>
      <webElementGuid>d1559c53-cdde-43ad-8a49-185e234295b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MessagingDestinationControlList:MessagingDestinationControlListScreen:MessagingDestinationControlList_RestartMessagingEngineButton-btnInnerEl&quot;)</value>
      <webElementGuid>eb19eabd-48b8-4ddd-8cd4-62ce6c638a10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='MessagingDestinationControlList:MessagingDestinationControlListScreen:MessagingDestinationControlList_RestartMessagingEngineButton-btnInnerEl']</value>
      <webElementGuid>c3c4d665-04be-4cb1-bd2e-780890ec02f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='MessagingDestinationControlList:MessagingDestinationControlListScreen:MessagingDestinationControlList_RestartMessagingEngineButton-btnEl']/span[2]</value>
      <webElementGuid>4f1aeb1b-5d67-48e0-9dcf-88e79327a830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='e'])[1]/following::span[4]</value>
      <webElementGuid>9bc6072a-b898-4271-afbf-d87867c66837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[1]/preceding::span[10]</value>
      <webElementGuid>3143da32-edd1-47a0-8e42-efa570e7da98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/a[3]/span/span/span[2]</value>
      <webElementGuid>2228b307-04c6-4bb0-a848-114043b3a292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
