<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Suspend</name>
   <tag></tag>
   <elementGuidId>031e94f3-fb40-4a88-a78b-2d348b194b52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id, 'SuspendButton')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>16645fa0-e31c-49cc-85a5-2ec9c9d6ad9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SuspendButton</value>
      <webElementGuid>4774195d-98ad-4458-9511-3126d68977fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>56a67abd-55d4-4c4e-836e-50a055f78e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>bc694a90-18bd-4ae9-b4de-ff51024a0acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-toolbar-small</value>
      <webElementGuid>622bdfe8-51bf-4ec7-b868-ca3dd87cd65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suspend</value>
      <webElementGuid>42bdba4d-e0f7-4000-a6d1-4043c17118da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MessagingDestinationControlList:MessagingDestinationControlListScreen:MessagingDestinationControlList_SuspendButton-btnInnerEl&quot;)</value>
      <webElementGuid>2a2cf76e-77d3-4240-ac48-475b5830586c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='MessagingDestinationControlList:MessagingDestinationControlListScreen:MessagingDestinationControlList_SuspendButton-btnInnerEl']</value>
      <webElementGuid>6788c139-36ea-4180-ab51-cb1dfb6b1870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='MessagingDestinationControlList:MessagingDestinationControlListScreen:MessagingDestinationControlList_SuspendButton-btnEl']/span[2]</value>
      <webElementGuid>32e18c70-547f-4495-bf6f-5717e218652d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Queues'])[2]/following::span[4]</value>
      <webElementGuid>28b2154a-214a-4803-80a4-892812eaffb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template To Schema Map'])[1]/following::span[6]</value>
      <webElementGuid>3b7a85f9-4b36-4a4a-a8c6-96f2acd42820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/a/span/span/span[2]</value>
      <webElementGuid>0d773c7c-135f-4037-b9a3-1f35b516dea1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
