<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_MessageQueues</name>
   <tag></tag>
   <elementGuidId>46b00a08-a242-42a3-aa6f-aaaba1967641</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id, 'MessagingDestinationControlListScreen')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e663a887-c233-42c7-92a5-02ef4e7bda2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>g-title</value>
      <webElementGuid>df62e03f-a5d8-45f2-b271-c26bf87bdffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MessagingDestinationControlListScreen</value>
      <webElementGuid>f361eca0-c338-4973-bfdc-fa9c035d9b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Message Queues</value>
      <webElementGuid>1877529c-8f4f-4e32-bc69-3c45c79c5a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MessagingDestinationControlList:MessagingDestinationControlListScreen:ttlBar&quot;)</value>
      <webElementGuid>0a3eadae-c6af-43a6-a9c7-3b91d49aa982</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='MessagingDestinationControlList:MessagingDestinationControlListScreen:ttlBar']</value>
      <webElementGuid>a648b1af-9317-4218-be28-5fad18c6ca85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title-1962-textEl']/span</value>
      <webElementGuid>8d505591-abae-4cc0-a010-6d0fc8953dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template To Schema Map'])[1]/following::span[2]</value>
      <webElementGuid>7f114b49-0f1c-429a-bf9d-d9b1a1832cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Content Analyzer'])[1]/following::span[3]</value>
      <webElementGuid>77c28800-0971-461e-a089-cfac5b3d4512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/preceding::span[2]</value>
      <webElementGuid>67eb2a47-61f9-46a8-b7a5-9db5d840d439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/div/span</value>
      <webElementGuid>7ada4596-7550-4fa0-a4c9-d5a7a85bb23b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
