<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectToggleButtonByLabelText</name>
   <tag></tag>
   <elementGuidId>3de53ffd-6d20-40ca-8c54-5e52947ed1b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='${text}']//following-sibling::div//div[@role='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='${text}']//following-sibling::div//div[@role='button']</value>
      <webElementGuid>8394a7c1-20a9-4227-b06e-37121294af11</webElementGuid>
   </webElementProperties>
</WebElementEntity>
