<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectByIndex</name>
   <tag></tag>
   <elementGuidId>2010350b-99a3-4fe2-b629-71772e848b89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//select)[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//select)[${index}]</value>
      <webElementGuid>44485786-1b1a-4025-9a7e-fdf18b352cad</webElementGuid>
   </webElementProperties>
</WebElementEntity>
