<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectUnderText</name>
   <tag></tag>
   <elementGuidId>2e7349b0-68fd-49a5-bd8b-4975923d4255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='${text}']/..//following-sibling::div//select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='${text}']/..//following-sibling::div//select</value>
      <webElementGuid>2504c670-33b6-4351-b623-18dae60a98c7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
