<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_totalPageNum</name>
   <tag></tag>
   <elementGuidId>2ddbcf1a-c028-4418-9780-63db67ee908b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='gw-paging--label-post']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='gw-paging--label-post']</value>
      <webElementGuid>6b05af83-1370-4ec9-8561-81bca2901f55</webElementGuid>
   </webElementProperties>
</WebElementEntity>
