<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aByContainsText</name>
   <tag></tag>
   <elementGuidId>d46896d3-865a-4d5c-9708-d3d7f62803fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(text(),'${text}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(text(),'${text}')]</value>
      <webElementGuid>657c5121-81bd-476b-9c1e-1213e1ca7e5e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
