<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aByText</name>
   <tag></tag>
   <elementGuidId>ac134a9e-4117-45b5-ae6d-40197cde081c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[text()='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[text()='${text}']</value>
      <webElementGuid>c8fd8de5-8a1a-43e7-875c-6231a3c7eda5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
