<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pByClassName</name>
   <tag></tag>
   <elementGuidId>4b851fe9-148d-44eb-9b83-986fc176302b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[@class='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[@class='${text}']</value>
      <webElementGuid>f1a80176-817c-4c80-8952-cb7f81922831</webElementGuid>
   </webElementProperties>
</WebElementEntity>
