<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2ByText_SectionHeader</name>
   <tag></tag>
   <elementGuidId>941d8481-3601-4b47-85ce-7741b489aa5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[text()='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[text()='${text}']</value>
      <webElementGuid>8f065ec8-cbf6-4769-93f9-06d67c039a39</webElementGuid>
   </webElementProperties>
</WebElementEntity>
