<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5ByText</name>
   <tag></tag>
   <elementGuidId>1a370abb-e550-4485-8f6d-6a9e52ae1c03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h5[text()='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h5[text()='${text}']</value>
      <webElementGuid>1a5962b6-7863-40fa-8fbf-f3b4224a228e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
