<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnByContainsText</name>
   <tag></tag>
   <elementGuidId>5f3bedb0-4cfd-405f-a5bb-0ed098749574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(text(),'${text}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(text(),'${text}')]</value>
      <webElementGuid>46c19d8c-30e6-4345-9605-c8d4ab1a1b79</webElementGuid>
   </webElementProperties>
</WebElementEntity>
