<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divByID</name>
   <tag></tag>
   <elementGuidId>738508e3-5b39-4c65-8b57-98c72999a295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='${text}']</value>
      <webElementGuid>b32afb3b-75cc-4c98-b833-90f6df679cd7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
