<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_ReturnToGW</name>
   <tag></tag>
   <elementGuidId>bf16b249-1bd9-47b2-a816-11a7f7a17b94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(contains(text(), 'Return to') or contains(., 'Return to')) and @class = 'gw-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>17f973b6-d28d-442f-8223-de5b68732adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Return to</value>
      <webElementGuid>60ba0928-4374-412a-8840-0cdfa8864005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>e5f39839-7c3c-4476-bd8b-e3696186946d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReturnToApp</value>
      <webElementGuid>cfeb7b16-84ae-4895-8e90-ef9ed2668d19</webElementGuid>
   </webElementProperties>
</WebElementEntity>
