<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_Batch</name>
   <tag></tag>
   <elementGuidId>2b6d72a6-ed7d-4e5d-b309-6dbf1040c695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = '${BatchName}' or . = '${BatchName}') and @class = 'gw-label']/../../../..</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = '${BatchName}' or . = '${BatchName}') and @class = 'gw-label']/../../../..</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>456ea210-d4f8-4d41-b14d-563567a90b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${BatchName}</value>
      <webElementGuid>dfc59bb1-8534-440a-9a20-c370a3f71fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>b4634fbb-3773-4559-8d37-e5cb9bd2b53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[(text() = '${BatchName}' or . = '${BatchName}') and @class = 'gw-label']/../../../..</value>
      <webElementGuid>a9fee00f-ff37-45c8-a1cc-61b57785f9b4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
