<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxContainsTextAndIndex</name>
   <tag></tag>
   <elementGuidId>1cca4f36-1aaf-4f90-84c9-608547b32848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(text(),'${text}')]/preceding-sibling::div//input/preceding-sibling::div)[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(text(),'${text}')]/preceding-sibling::div//input/preceding-sibling::div)[${index}]</value>
      <webElementGuid>086ea3a6-bf6d-4859-9de1-46aafb25032d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
