<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxAfterContainsText</name>
   <tag></tag>
   <elementGuidId>f12a64ad-afe2-4d58-be8a-3f58edea2944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'${text}')]/following-sibling::div//div[@role='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'${text}')]/following-sibling::div//div[@role='checkbox']</value>
      <webElementGuid>2e9d132e-f262-41fc-aeef-96a3b71c763e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
