<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divByText</name>
   <tag></tag>
   <elementGuidId>1a975295-8162-4ce3-9725-69a209481f5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='${text}']</value>
      <webElementGuid>79347461-ccec-4b11-8bbc-9e38a0c9f727</webElementGuid>
   </webElementProperties>
</WebElementEntity>
