<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divByContainsText</name>
   <tag></tag>
   <elementGuidId>5a551c46-9478-4543-a48e-ff54b0e3c14e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'${text}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'${text}')]</value>
      <webElementGuid>ddd411b7-0f9d-4df7-b325-91b9afe449f0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
