<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divParentDivByText</name>
   <tag></tag>
   <elementGuidId>9db110ff-9802-4356-a187-9824582fd9cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='${text}']/parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='${text}']/parent::div</value>
      <webElementGuid>d09b1588-2242-4b70-88b9-ed9ad73bb8ce</webElementGuid>
   </webElementProperties>
</WebElementEntity>
