<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divUnderH3ByTextAndIndexAndClassName</name>
   <tag></tag>
   <elementGuidId>e2f984f0-2848-4fbe-bcf9-3f5da2d8c9c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h3[text()='${text}']/ancestor::div[1]/following-sibling::div//a[@class='${className}'])[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h3[text()='${text}']/ancestor::div[1]/following-sibling::div//a[@class='${className}'])[${index}]</value>
      <webElementGuid>2a39523a-fa96-414c-8090-269e830c8e0e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
