<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>smallTextBySubHeaderTitle</name>
   <tag></tag>
   <elementGuidId>4b0e50c3-5a7c-4ac1-8a7e-a1fb232c7f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h2[text()='${text}']/following-sibling::div/div//small)[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h2[text()='${text}']/following-sibling::div/div//small)[${index}]</value>
      <webElementGuid>c70222b3-a7c6-47be-9cf8-d38489ffe969</webElementGuid>
   </webElementProperties>
</WebElementEntity>
