<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputByAttributeValueText</name>
   <tag></tag>
   <elementGuidId>1c4b1784-3ff6-48e6-a7fa-26068af64519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='${value}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='${value}']</value>
      <webElementGuid>6ba02603-cf78-4002-bacf-46710245cd9f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
