<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputByID</name>
   <tag></tag>
   <elementGuidId>50b89e97-8551-45da-9b79-e162096a64d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='${text}']</value>
      <webElementGuid>f40ff1d3-59c8-4153-ad37-6658cb80a695</webElementGuid>
   </webElementProperties>
</WebElementEntity>
