<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputByAttributePlaceholderText</name>
   <tag></tag>
   <elementGuidId>9858e0e2-741d-4672-affe-74d58cd953c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@placeholder='${text}']</value>
      <webElementGuid>58235421-e742-4254-a23f-ae50b066902d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
