<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Select</name>
   <tag></tag>
   <elementGuidId>e748c4f5-2277-4386-b13a-ae98662ba8fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id, 'SearchResultsLV-${item}-_Select') or contains(@id, 'SearchLV-${item}-_Select')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4d13342-1b3e-488c-9258-9d98910d12ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>25912d5f-2604-46a4-adbf-2d66109be43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>g-actionable</value>
      <webElementGuid>f964048a-1148-4c6b-b6f8-9f625bad855c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchResultsLV-${item}-_Select</value>
      <webElementGuid>7f6ae1a9-eef6-4694-82cb-ed055d07c6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>ends with</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>21a24265-2360-41d3-bfff-7951c27f75bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@id, 'SearchResultsLV-${item}-_Select') or contains(@id, 'SearchLV-${item}-_Select')]</value>
      <webElementGuid>74d7e921-f890-4fa1-b4c1-add06c21ab8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='AccountFile_AccountSearch:OtherAccountSearchScreen:OtherAccountSearchResultsLV:0:Select']</value>
      <webElementGuid>d7e2345e-a335-4174-af82-43e0e31a2163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridview-2034-record-2351']/tbody/tr/td/div/a</value>
      <webElementGuid>3a861272-d035-455a-aee4-9ffb2d1c3dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>12a56e85-cda3-4aa5-ba77-e8426ab85dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::a[1]</value>
      <webElementGuid>35cc77b3-b5e4-48ab-8150-0ab056deb925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/following::a[1]</value>
      <webElementGuid>882604e1-a90e-41b9-973d-e3236c8668e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A010000021'])[1]/preceding::a[1]</value>
      <webElementGuid>9bf0cab6-8024-4e96-82a7-410d0d78ad56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PWC Test181115'])[1]/preceding::a[2]</value>
      <webElementGuid>94b8b7e8-d219-4945-aa85-e45e803aefeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>ee37f61e-a1e4-4433-a7c5-ca7ba1274d70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
