<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Payment_Next</name>
   <tag></tag>
   <elementGuidId>8e4e71be-55a0-4ef3-b301-82aa63f3de04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'ListPaging-next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eecc2f64-9383-4c7a-a481-2f2297df6c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ListPaging-next</value>
      <webElementGuid>223d264c-fb51-4683-9a79-50865e828a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-paging--button-next gw-paging--button</value>
      <webElementGuid>fcef65b8-5835-41b2-8963-89ff9a481c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>gwListView.page page:2 renderId:AccountPayments-AccountDetailPaymentsScreen-DirectBillPaymentsListDetail-AccountDBPaymentsLV-_ListPaging</value>
      <webElementGuid>5df42c2a-7060-4865-a18d-5bd045734513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-tooltip</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>d51f487e-4bde-47f8-8406-e815afc163b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseenter</name>
      <type>Main</type>
      <value>gwMouse.enter</value>
      <webElementGuid>e589ee63-3b86-4370-b595-a9ee75f7297a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mousemove</name>
      <type>Main</type>
      <value>gwTooltips.move</value>
      <webElementGuid>cb4ee7a9-4e69-445a-afe9-0b8535b1fb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseout</name>
      <type>Main</type>
      <value>gwTooltips.hide</value>
      <webElementGuid>856a5bc0-0e14-44b0-957f-4279be8f0748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c763619-7591-49e1-8db6-3a2bf380db8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountPayments-AccountDetailPaymentsScreen-DirectBillPaymentsListDetail-AccountDBPaymentsLV-_ListPaging-next&quot;)</value>
      <webElementGuid>90d02a08-ac01-472b-beb4-8119818d0278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='AccountPayments-AccountDetailPaymentsScreen-DirectBillPaymentsListDetail-AccountDBPaymentsLV-_ListPaging-next']</value>
      <webElementGuid>b483c857-d7eb-4601-85fe-11bf989f7ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountPayments-AccountDetailPaymentsScreen-DirectBillPaymentsListDetail-AccountDBPaymentsLV-_ListPaging']/div[5]</value>
      <webElementGuid>5656afa4-932c-4b71-ae43-a5506fa2f5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Received'])[1]/following::div[14]</value>
      <webElementGuid>add36274-cc43-40ef-9ed1-f5df2bb069eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[4]/following::div[26]</value>
      <webElementGuid>b4e0ef56-7d16-4a40-b4a3-1bbea6ce9036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Column Order &amp; Visibility'])[1]/preceding::div[6]</value>
      <webElementGuid>e66cb7de-1280-42e4-99f2-d8c5c1a8a962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Date'])[1]/preceding::div[14]</value>
      <webElementGuid>3817af33-016e-4345-8890-2bf128456280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div[5]</value>
      <webElementGuid>7e9ce9a8-0100-4678-9155-364ae59d352b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
