<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_CompanyName</name>
   <tag></tag>
   <elementGuidId>0994bf60-5a9a-4bcd-be04-ac9ae962c56c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and contains(@name, '-Name')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0ebe752-d926-49ab-8e2c-509857887265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bfb0d412-6115-4e4a-b0c1-9048f2599615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>-Name</value>
      <webElementGuid>9ded7cd3-0cba-438e-8924-10d0d8e4149a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-noTrack gw-focus</value>
      <webElementGuid>9890c54e-97c9-48b5-ae14-c0ca5901678b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountSearch-AccountSearchScreen-AccountSearchDV-GlobalContactNameInputSet-Name&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-noTrack gw-focus&quot;]</value>
      <webElementGuid>7fda6cc1-0bc2-40a3-aa13-240b86067474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='AccountSearch-AccountSearchScreen-AccountSearchDV-GlobalContactNameInputSet-Name']</value>
      <webElementGuid>d76739a5-271a-4bfb-8cb2-ca7aa0ed1e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountSearch-AccountSearchScreen-AccountSearchDV-GlobalContactNameInputSet-Name']/div/input</value>
      <webElementGuid>5321daf3-d9ce-433d-8fb5-4dc65147f4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/following::input[1]</value>
      <webElementGuid>1ce7c435-2590-487a-8db7-ab87d0c6d33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name is an exact match'])[1]/following::input[2]</value>
      <webElementGuid>5de1247a-bc98-4ffd-aa78-817afcf76eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company name is an exact match'])[1]/preceding::input[1]</value>
      <webElementGuid>62ea6ef2-3073-4f78-9b97-7f6bf9163b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax ID'])[1]/preceding::input[2]</value>
      <webElementGuid>83ca4638-d959-40e3-b611-2cd287057fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div/div/input</value>
      <webElementGuid>2f5e9a77-d12c-4585-bf70-32fa0629dd6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
