<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ZIPCode</name>
   <tag></tag>
   <elementGuidId>9295f0c8-8387-46d3-892a-97ae983a1597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='NewContact-ContactPanelSet-ContactCV-ContactDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-PostalCode']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and contains(@name, 'PostalCode')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76430ca7-152c-476e-b0ee-dc35eb398f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bab5627-5e4f-4493-9a49-4976f3e6f3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PostalCode</value>
      <webElementGuid>fb06cfa8-2c7b-4473-82e0-74b8f1d2ecd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#####-####</value>
      <webElementGuid>0e689a17-f68b-4d13-a6ea-3f1446b20551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-char-threshold</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a8085fcd-68fb-4ec7-a200-0e420dc43024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-dependent-fields</name>
      <type>Main</type>
      <value>NewContact-ContactPanelSet-ContactCV-ContactDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-City,NewContact-ContactPanelSet-ContactCV-ContactDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-County,NewContact-ContactPanelSet-ContactCV-ContactDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-State,NewContact-ContactPanelSet-ContactCV-ContactDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-Country</value>
      <webElementGuid>81daa2be-9b7b-452a-a2aa-380bbfb402df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-input-mask</name>
      <type>Main</type>
      <value>#####-####</value>
      <webElementGuid>b7c5eb7b-85a7-48df-b02f-981e2b33be28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9bd1f139-f8ef-4c2f-8508-010abea365a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-input</name>
      <type>Main</type>
      <value>gwInputs.inputEventNotifySystems</value>
      <webElementGuid>ead309b9-f4a0-45f3-a7b7-70824588c877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-focus</name>
      <type>Main</type>
      <value>gwTextValue.autocomplete</value>
      <webElementGuid>9f222130-d186-4ef9-8565-8dc01bf85bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-key</name>
      <type>Main</type>
      <value>gwTextValue.chooseCurrentAutocompleteEntry key:13</value>
      <webElementGuid>70a33490-3b88-41e6-adff-c8b83c4b29c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-copy</name>
      <type>Main</type>
      <value>gwInputs.copyEventNotifySystems</value>
      <webElementGuid>e07a2a7e-e2f8-43e5-a538-964f29d94c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>513ffd6c-9041-4e6a-ad2d-f25ef362c5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewContact-ContactPanelSet-ContactCV-ContactDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-PostalCode&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[1]</value>
      <webElementGuid>f741e3f7-5407-411b-bdab-ebfc9f6db8b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='NewContact-ContactPanelSet-ContactCV-ContactDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-PostalCode']</value>
      <webElementGuid>c5e175c1-d719-4273-b024-f7d95144d9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewContact-ContactPanelSet-ContactCV-ContactDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-PostalCode']/div/input</value>
      <webElementGuid>3420adfa-3acb-4cb5-ad57-e2138915ece4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP Code'])[1]/following::input[1]</value>
      <webElementGuid>49362561-be02-4405-8df1-4bfcfa3e4766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::input[1]</value>
      <webElementGuid>3c63f2fb-ecf8-4c67-89ba-ae380fdf5023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Type'])[1]/preceding::input[1]</value>
      <webElementGuid>3cc6cb0d-f8fc-44aa-85cc-89272e33180d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::input[1]</value>
      <webElementGuid>8a5c81c9-8d88-4535-821c-ef26a21557d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div[2]/div/div/div/input</value>
      <webElementGuid>a6fa5b9a-d927-4f27-a26e-4516306155ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
