<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Fname</name>
   <tag></tag>
   <elementGuidId>12a899a9-1855-441c-a7f0-e75443280a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name=&quot;FNOLWizard-FNOLWizard_FindPolicyScreen-FNOLWizardFindPolicyPanelSet-GlobalPersonNameInputSet-FirstName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name=&quot;FNOLWizard-FNOLWizard_FindPolicyScreen-FNOLWizardFindPolicyPanelSet-GlobalPersonNameInputSet-FirstName&quot;]</value>
      <webElementGuid>714b75d7-72b4-47f9-b186-3009239400b8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
