<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_TabsMoreOptions</name>
   <tag></tag>
   <elementGuidId>b8c5635a-4762-4d9a-9c0f-09caa711bb54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'TabBarWidget--more-options']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a8ac88f-d11e-4800-8753-d154ce10ee0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TabBarWidget--more-options</value>
      <webElementGuid>c4fb0b69-8fb8-42f2-aca0-163a9548c360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnIconEl</value>
      <webElementGuid>5339f547-6ddd-444c-9598-52d376f64540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>714323d7-3d40-414e-a5c7-d06c0adbf684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>5e490cab-08b9-4454-b14e-0a20a92d1b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el x-btn-icon-el-default-toolbar-small x-toolbar-more-icon </value>
      <webElementGuid>cb06063a-994c-4296-865c-37b4432054e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>760b4a05-e156-4c79-af82-8903443cf4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:tabs-menu-trigger-btnIconEl&quot;)</value>
      <webElementGuid>87027bee-05e3-4ddc-908c-fc462b9a1591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id=':tabs-menu-trigger-btnIconEl']</value>
      <webElementGuid>831881c7-1541-4678-8f22-1c49b1836769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id=':tabs-menu-trigger-btnEl']/span</value>
      <webElementGuid>2127f0d0-8108-4eeb-b53c-daf55e74ca9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='m'])[1]/following::span[3]</value>
      <webElementGuid>977c6fb4-5b7c-4182-8779-856572297b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Date:'])[1]/preceding::span[20]</value>
      <webElementGuid>76fc2eba-c1e1-4075-8d6a-cee9861a0461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov 20, 2018'])[1]/preceding::span[21]</value>
      <webElementGuid>5135d98e-7f7f-4d7d-bd39-27a3da81ca29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span/span/span</value>
      <webElementGuid>9a0fc1b1-c183-48f6-8d4e-d814e29b9c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
