<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_Search_SideMenuLink</name>
   <tag></tag>
   <elementGuidId>95912b99-53f0-453f-8181-ddda56f8cb39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'SearchGroup-MenuLinks-SearchGroup_${item}Search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c41d2f15-2b97-4edb-818f-a8d9f66088bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchGroup-MenuLinks-SearchGroup_${item}Search</value>
      <webElementGuid>54972a1c-e399-49a2-903a-ff9a62c3f84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>596d4638-e5df-47bd-9933-207d9d1cf85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>da489a3e-fe39-42dc-aed6-9ec9ad696b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>019c0cde-2440-40c8-865b-3bef48823652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${item}</value>
      <webElementGuid>ecffa14f-1091-4e02-a4e3-d9e856e2a738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'DesktopGroup-MenuLinks-DesktopGroup_Desktop${item}' or @id = 'DesktopGroup-MenuLinks-DesktopGroup_${item}']</value>
      <webElementGuid>3aea7001-1172-4db7-b6a9-0cb2fcf4dbc1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
