<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_TabBar</name>
   <tag></tag>
   <elementGuidId>590a7a3a-7081-42c4-a37d-728b4becf76c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;TabBar:AccountTab-btnWrap&quot;)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id, 'TabBar-${item}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c2b90f6-28d0-4983-9d4f-32b07f18b3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-wrap</value>
      <webElementGuid>0a2c045a-2234-4758-b0c5-1097104cdb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TabBar-${item}</value>
      <webElementGuid>0f8f11a2-4a50-44c5-a9c7-63f4f9014d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>8a61c02c-0582-4f41-83c6-cf351121d9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8d046fd0-eddc-4854-ad21-a38403710b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TabBar:AccountTab-btnWrap&quot;)</value>
      <webElementGuid>1ede76dd-a294-446b-bfb4-b2b86d468cec</webElementGuid>
   </webElementProperties>
</WebElementEntity>
