<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_TabBarWrap</name>
   <tag></tag>
   <elementGuidId>cb99a896-ffcc-424a-ab50-46089f529d0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;TabBar:AccountTab-btnWrap&quot;)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'TabBar:${item}Tab-btnWrap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d00e84eb-10b6-4f29-baa5-70b04f38e377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-wrap</value>
      <webElementGuid>0329ada6-9813-41be-af53-c01926744fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TabBar:${item}Tab-btnWrap</value>
      <webElementGuid>be701a37-986b-4795-a2ad-a55646fb9c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>02325a38-9276-4211-9519-56a60b5f85f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>fce3d531-41bf-439b-be35-afb131f3da39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TabBar:AccountTab-btnWrap&quot;)</value>
      <webElementGuid>12b6267f-7d4b-4fae-8dab-ae103eb07472</webElementGuid>
   </webElementProperties>
</WebElementEntity>
