<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_ScreenName</name>
   <tag></tag>
   <elementGuidId>85a3823b-b147-475b-a826-ebae51fb16c4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57dc527e-bafc-4693-80f7-34b70a13453d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-HOPDwellingScreen-ttlBar</value>
      <webElementGuid>d839c960-b2b2-42b6-9877-826e0ff863cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-TitleBarWidget gw-StyleContainer--CenterPanelWidget gw-isScreenTitle</value>
      <webElementGuid>551d87e5-e66d-4bdb-8201-9ea02ed6dd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dwelling</value>
      <webElementGuid>3237f6f8-fba3-4bfb-9bb6-e4c92bab7399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-HOPDwellingScreen-ttlBar&quot;)</value>
      <webElementGuid>3d44d64b-2643-4bc2-a149-06c965e0d6a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-HOPDwellingScreen-ttlBar']</value>
      <webElementGuid>5e83596e-4898-43f8-a9eb-9192c153e2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gw-center-title-toolbar']/div</value>
      <webElementGuid>ff3a929a-33ab-4c39-939c-3de96662bab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alice Applegate'])[1]/following::div[3]</value>
      <webElementGuid>7679da18-8459-4250-8ca4-1071eab72d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underwriter:'])[1]/following::div[4]</value>
      <webElementGuid>76a8f61c-f4a6-4925-83e6-e9def5351eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ba'])[1]/preceding::div[4]</value>
      <webElementGuid>daa7b20b-59cf-4c8a-ba4f-4ff29dbd5a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[2]/div/div[3]/div</value>
      <webElementGuid>12054fe9-c5a5-478f-840b-b3a3dd833bb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
