<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_Desktop_SideMenuLink</name>
   <tag></tag>
   <elementGuidId>901250ff-8614-4842-b8e9-87df6da5e482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'DesktopGroup-MenuLinks-DesktopGroup_Desktop${item}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89143be9-dcc8-487d-85e9-a5be1bb6fa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DesktopGroup-MenuLinks-DesktopGroup_Desktop${item}</value>
      <webElementGuid>beddc2c4-7342-49c3-8ec2-55fd6d1a0058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>388d150e-d419-4543-bc32-0e00a2e85a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>4015531d-ac8f-4218-8767-6874ae741502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>137aa8e0-81d2-4645-8cb8-84c4ee6d1894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${item}</value>
      <webElementGuid>56855d3b-a7ff-45df-8ec0-4a9b19c6afa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'DesktopGroup-MenuLinks-DesktopGroup_Desktop${item}' or @id = 'DesktopGroup-MenuLinks-DesktopGroup_${item}']</value>
      <webElementGuid>7a611e1a-0e90-45b7-b8d0-24c894e3ba98</webElementGuid>
   </webElementProperties>
</WebElementEntity>
