<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_SideMenu</name>
   <tag></tag>
   <elementGuidId>aa92792e-2515-4ca7-a2b6-babc91e8081a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@class, 'x-tree-node-text ') and (contains(text(), '${item}') or contains(., '${item}'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d00f71cf-e136-49ca-a10c-55d864d48201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tree-node-text </value>
      <webElementGuid>69943c28-e259-4f23-9699-a10875cbe9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-1302</value>
      <webElementGuid>2994ea98-ace6-4eb7-9526-d8dff0ce424a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${item}</value>
      <webElementGuid>5b275541-983b-410a-ac1a-3ea2deb494ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-1302&quot;)</value>
      <webElementGuid>572084e5-7ba7-42f8-9bf2-9b27deca6abc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
