<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_Account_SideMenuLink</name>
   <tag></tag>
   <elementGuidId>6b323a42-2856-4935-92d7-3207d839b861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'AccountGroup-MenuLinks-AccountGroup_AccountDetail${item}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d40048ce-61b4-446f-bf30-e669d9fc2bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountGroup-MenuLinks-AccountGroup_AccountDetail${item}</value>
      <webElementGuid>e7886247-fa81-474f-a71d-27083fbdb604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>d5fc82af-49f7-4a63-a139-69af6829faff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>df489376-5e2d-424a-9ca4-9c7313029367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4ad1c002-c6c8-4e87-ab5a-3654ea05e0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${item}</value>
      <webElementGuid>3dc091a6-cedd-4b76-b846-18cb4fee1801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'DesktopGroup-MenuLinks-DesktopGroup_Desktop${item}' or @id = 'DesktopGroup-MenuLinks-DesktopGroup_${item}']</value>
      <webElementGuid>bf2662c3-5d39-42fa-8122-977bdf512080</webElementGuid>
   </webElementProperties>
</WebElementEntity>
