<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wel_Policy_SideMenuLink</name>
   <tag></tag>
   <elementGuidId>a7c8703b-fd35-48f2-a8c2-8f1e123fb852</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'PolicyGroup-MenuLinks-PolicyGroup_PolicyDetail${item}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61d463b0-b78e-4575-94e3-1b584bb1d026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PolicyGroup-MenuLinks-PolicyGroup_PolicyDetail${item}</value>
      <webElementGuid>46d79039-5239-4153-a915-884453a4abea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>3b68fa4e-5b1e-4455-8684-e4a24722c339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>530ffb4e-6f5b-4159-a846-5d8299862474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a70f74b5-d7cb-40c4-b55b-895a518587be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${item}</value>
      <webElementGuid>cf38b876-cb2a-4c2c-91da-793d31e15ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'DesktopGroup-MenuLinks-DesktopGroup_Desktop${item}' or @id = 'DesktopGroup-MenuLinks-DesktopGroup_${item}']</value>
      <webElementGuid>b0937189-87dd-412a-8fe5-ccc21a88bb12</webElementGuid>
   </webElementProperties>
</WebElementEntity>
