<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropDownCount</name>
   <tag></tag>
   <elementGuidId>39dd12b1-f962-430e-8853-1a30dbc29823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ManufactureComponentsOrFinalProducts_Ext&quot;]/span/div/div/ng-transclude/md-input-container/ng-transclude/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ManufactureComponentsOrFinalProducts_Ext&quot;]/span/div/div/ng-transclude/md-input-container/ng-transclude/div</value>
      <webElementGuid>6c7ffd52-a2d8-4aa0-bd22-195b6644ed1a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
