<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconByClassText</name>
   <tag></tag>
   <elementGuidId>7e637837-ec0f-45cd-ae5a-74152e99fe41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[@class='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//i[@class='${text}']</value>
      <webElementGuid>d9989dfd-7fe5-424a-929b-275e2e8b7616</webElementGuid>
   </webElementProperties>
</WebElementEntity>
