<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputByType</name>
   <tag></tag>
   <elementGuidId>9e5a9d80-801d-47d1-94a3-5a21f43ffd6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type='${type}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type='${type}']</value>
      <webElementGuid>da61c550-599f-4541-a660-7279489d5368</webElementGuid>
   </webElementProperties>
</WebElementEntity>
